[project]
name = "data-my-fpl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.13.2",
    "polars>=1.35.2",
    "requests>=2.32.5",
    "rich>=14.2.0",
    "selectolax>=0.4.4",
]
